# See LICENSE file for copyright and license details.

Vagrant.configure("2") do |config|
  config.vm.box = "__virtual_machine__"
  config.vm.network "private_network", ip: "192.168.32.10"
  config.vm.synced_folder ".", "__synced_folder__/__module__"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.name = "__filename__"
  end

  config.vm.provision "shell", inline: <<-SHELL
  SHELL
end
